// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_tiyvV9fEMr57te5tDnZjiueU8EtJeL0',
    appId: '1:86391809946:web:9ee510d64f62a4a719bc23',
    messagingSenderId: '86391809946',
    projectId: 'baboon-9953e',
    authDomain: 'baboon-9953e.firebaseapp.com',
    storageBucket: 'baboon-9953e.appspot.com',
    measurementId: 'G-P8Z61STFXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABKzhgbBljp4bOH5cMLx53-x1K0bgaVDw',
    appId: '1:86391809946:android:3e542ed38def342119bc23',
    messagingSenderId: '86391809946',
    projectId: 'baboon-9953e',
    storageBucket: 'baboon-9953e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs-kiblt_DYM1nQ7EEGGGuuk9EPAVI6t4',
    appId: '1:86391809946:ios:4a7ac7d019cc2a8019bc23',
    messagingSenderId: '86391809946',
    projectId: 'baboon-9953e',
    storageBucket: 'baboon-9953e.appspot.com',
    iosClientId: '86391809946-eppa1gsni03o52cbfbn6c7dbf7920iie.apps.googleusercontent.com',
    iosBundleId: 'com.example.vooms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs-kiblt_DYM1nQ7EEGGGuuk9EPAVI6t4',
    appId: '1:86391809946:ios:4a7ac7d019cc2a8019bc23',
    messagingSenderId: '86391809946',
    projectId: 'baboon-9953e',
    storageBucket: 'baboon-9953e.appspot.com',
    iosClientId: '86391809946-eppa1gsni03o52cbfbn6c7dbf7920iie.apps.googleusercontent.com',
    iosBundleId: 'com.example.vooms',
  );
}
